# L09
## Author-Zhuoyu Peng
### Instructions

Please complete the lab exercise for this week before following these steps to complete your assignment.

1. Leverage Naïve Bayes algorithm to classify build a model using the data from previous milestones.
2. Briefly summarize your findings on using Naïve Bayes.
3. Is Naïve Bayes more accurate than the regression model you used in Milestone 3?

In [1]:
# Load necessary libraries
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

Data are obtained from https://www.kaggle.com/snehal1405/yellow-stone-national-park
#####  "The purpose of possible analysis of this dataset is to propose and inspect the factors that may influence people’s visits to Yellowstone over years, such as weather and climate, travel costs, other macroeconomic factors, and so on."

In [2]:
file = 'datasets_25763_32828_ysnp.csv'
df = pd.read_csv(file)

In [3]:
df.iloc[::,:5].head() 

Recreation Visits  LowestTemperature(F)  HighestTemperature(F)  \
0              30621                 -17.0                   37.0   
1              28091                 -17.0                   42.0   
2              26778                 -19.0                   41.0   
3              24699                 -22.0                   43.0   
4              24766                 -14.0                   41.0   

   WarmestMinimumTemperature(F)  ColdestMaximumTemperature(F)  
0                          23.0                          10.0  
1                          27.0                           2.0  
2                          26.0                           5.0  
3                          30.0                           6.0  
4                          28.0                          14.0

Showing the first five columns of the data, to have a brief idea what data are in the data set. 

In [4]:
df.columns

Index(['Recreation Visits', 'LowestTemperature(F)', 'HighestTemperature(F)',
       'WarmestMinimumTemperature(F)', 'ColdestMaximumTemperature(F)',
       'AverageMinimumTemperature(F)', 'AverageMaximumTemperature(F)',
       'MeanTemperature(F)', 'TotalPrecipitation(In)', 'TotalSnowfall(In)',
       'Max 24hrPrecipitation(In)', 'Max 24hrSnowfall(In)', 'Year/Month/Day',
       '3month Percent Change Airfare Costs',
       '3month Percent Change Food Away From Home Costs',
       '3month Percent Change Gasoline Costs',
       '3month Percent Change Jet Fuel Costs', 'Consumer Price Index',
       'Consumer Sentiment Index', 'Unemployment Rate'],
      dtype='object')

Using `columns`, we can more clearly see whe whole data set.

In [5]:
df.shape

(372, 20)

Data has 372 observations, and 20 attributes in total.

In [6]:
df.dtypes

Recreation Visits                                    int64
LowestTemperature(F)                               float64
HighestTemperature(F)                              float64
WarmestMinimumTemperature(F)                       float64
ColdestMaximumTemperature(F)                       float64
AverageMinimumTemperature(F)                       float64
AverageMaximumTemperature(F)                       float64
MeanTemperature(F)                                 float64
TotalPrecipitation(In)                             float64
TotalSnowfall(In)                                  float64
Max 24hrPrecipitation(In)                          float64
Max 24hrSnowfall(In)                               float64
Year/Month/Day                                      object
3month Percent Change Airfare Costs                float64
3month Percent Change Food Away From Home Costs    float64
3month Percent Change Gasoline Costs               float64
3month Percent Change Jet Fuel Costs               float

Naïve Bayes model requires categorical data, so we need to change to categorical data. But let's select out some features first since some of them are simialr. 

Selected features: MeanTemperature, TotalPrecipitation, TotalSnowFall, Year/Month/Day, Consumer Price Index, and Consumer Sentiment Index

Next, we need to categorize and encode each one.

Let's do MeanTemperature first.

In [7]:
#calculate the mean of MeanTemp 
print('Median of MeanTemp:', df['MeanTemperature(F)'].median())

Median of MeanTemp: 37.8


37.8F is the median of MeanTemp, we can group temperature below and include 38 as "low", and temperature beyond 38 as "high"

In [8]:
#select MeanTemperature lower and equal than 38.0 as replace "low"
low = df['MeanTemperature(F)'] <= 38.0
#select MeanTemperature greater than 38.0 as replace "high"
high = df['MeanTemperature(F)'] > 38.0
df.loc[low, 'MeanTemperature(F)'] = 'low'
df.loc[high, 'MeanTemperature(F)'] = 'high'

Group TotalPrecipitation into category

In [9]:
#calculate the mean the Total Precipitation
print('Median of total precipitation:', df['TotalPrecipitation(In)'].median())

Median of total precipitation: 1.2


1.2 inch is the median of total precipitation, we can group precipitation below and include 1.2 as "low", and beyond 1.2 as "high"

In [10]:
#select total precipitation lower and equal than 1.2 as replace "low"
low = df['TotalPrecipitation(In)'] <= 1.2
#select total precipitation greater than 1.2 as replace "high"
high = df['TotalPrecipitation(In)'] > 1.2
df.loc[low, 'TotalPrecipitation(In)'] = 'low'
df.loc[high, 'TotalPrecipitation(In)'] = 'high'

Group TotalSnowFall into category

In [11]:
#calculate the mean the Totalsnow fall
print('Median of total snow fall:', df['TotalSnowfall(In)'].median())

Median of total snow fall: 4.5


4.5 inch is the median of total precipitation, we can group snowfall below and include 4.5 as "low", and beyond 4.5 as "high"

In [12]:
#select total snowfall lower and equal than 4.5 as replace "low"
low = df['TotalSnowfall(In)'] <= 4.5
#select total snowfall greater than 4.5 as replace "high"
high = df['TotalSnowfall(In)'] > 4.5
df.loc[low, 'TotalSnowfall(In)'] = 'low'
df.loc[high, 'TotalSnowfall(In)'] = 'high'

Group consumer price index into category

In [13]:
#calculate the mean the consumer price index
print('Median of comsumer price index:', df['Consumer Price Index'].median())

Median of comsumer price index: 0.2


0.2 inch is the median of consumer price index, we can group price index below and include 0.2 as "low", and beyond 0.2 as "high"

In [14]:
#select price index lower and equal than 0.2 as replace "low"
low = df['Consumer Price Index'] <= 0.2
#select price index greater than 0.2 as replace "high"
high = df['Consumer Price Index'] > 0.2
df.loc[low, 'Consumer Price Index'] = 'low'
df.loc[high, 'Consumer Price Index'] = 'high'

Group consumer semtiment index into category

In [15]:
#calculate the mean the sentiment index
print('Median of sentiment price index:', df['Consumer Sentiment Index'].median())

Median of sentiment price index: 90.1


90.1 inch is the median of consumer sentiment index, we can group sentiment index below and include 90.1 as "low", and beyond 90.1 as "high"

In [16]:
#select sentiment index lower and equal than 90.1 as replace "low"
low = df['Consumer Sentiment Index'] <= 90.1
#select sentiment index greater than 90.1 as replace "high"
high = df['Consumer Sentiment Index'] > 90.1
df.loc[low, 'Consumer Sentiment Index'] = 'low'
df.loc[high, 'Consumer Sentiment Index'] = 'high'

Create a dataframe that only contains selected featueres. 

In [17]:
new_df = df[['Recreation Visits','MeanTemperature(F)','TotalPrecipitation(In)','TotalSnowfall(In)', 'Year/Month/Day', 
           'Consumer Price Index', 'Consumer Sentiment Index']]
new_df.head()

Recreation Visits MeanTemperature(F) TotalPrecipitation(In)  \
0              30621                low                    low   
1              28091                low                    low   
2              26778                low                   high   
3              24699                low                    low   
4              24766                low                    low   

  TotalSnowfall(In) Year/Month/Day Consumer Price Index  \
0              high       2016/1/1                  low   
1              high       2015/1/1                  low   
2              high       2014/1/1                 high   
3              high       2013/1/1                 high   
4              high       2012/1/1                 high   

  Consumer Sentiment Index  
0                     high  
1                     high  
2                      low  
3                      low  
4                      low

Next, encode each category, except date first.

In [18]:
# Construct new categorical variables (encoding)
cat_list=['MeanTemperature(F)','TotalPrecipitation(In)','TotalSnowfall(In)', 
           'Consumer Price Index', 'Consumer Sentiment Index']
new_df = pd.get_dummies(new_df, columns= cat_list)

Next, we need take care of dates. Only months matter, so we extract month

In [19]:
#Constrcut new date variable, named Month
new_df['Month'] = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 
               'Aug', 'Sep', 'Oct', 'Nov', 'Dec'] *int(len(df)/12)

new_df = pd.get_dummies(new_df, columns = ['Month'])
new_df.drop(['Year/Month/Day'], axis= 1, inplace=True)

Finally, we also need to encode the target labels Recreation Visits

In [20]:
new_df['Recreation Visits'].median()

55627.5

55627.5  inch is the median of recreation visits, we can group recreation visit below and include 55627.5 as "low", and beyond 55627.5 as "high"

In [21]:
#select Recreation Visits lower and equal than 0.2 as replace "low"
low = new_df['Recreation Visits'] <= 55627.5
#select Recreation Visits greater than 0.2 as replace "high"
high = new_df['Recreation Visits'] > 55627.5
new_df.loc[low, 'Recreation Visits'] = 'low'
new_df.loc[high, 'Recreation Visits'] = 'high'

In [22]:
# le = preprocessing.LabelEncoder()
# new_df['Recreation Visits'] = le.fit_transform(new_df['Recreation Visits'])

In [23]:
new_df.iloc[::,:5].head()

Recreation Visits  MeanTemperature(F)_high  MeanTemperature(F)_low  \
0               low                        0                       1   
1               low                        0                       1   
2               low                        0                       1   
3               low                        0                       1   
4               low                        0                       1   

   TotalPrecipitation(In)_high  TotalPrecipitation(In)_low  
0                            0                           1  
1                            0                           1  
2                            1                           0  
3                            0                           1  
4                            0                           1

Finally, take a brief looka at our data, which should be ready for modeling.

First, we meed to split the data set into training and testing set.

In [24]:
from sklearn.model_selection import train_test_split
#select feature columns
feature = new_df.columns.values.tolist()[1:]
#split dataset into training and testing 
X_train, X_test, y_train, y_test = train_test_split(new_df[feature],new_df['Recreation Visits'])

In [25]:
from sklearn.naive_bayes import BernoulliNB
# Define the model
model = BernoulliNB()
# Train the model with our votes dataset
model.fit(X_train, y_train)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [26]:
#predict the test data set
y_pred = model.predict(X_test)

#create a new data dataframe to store prediction and true values
result = pd.DataFrame ({'y_pre': y_pred,
         'true value': y_test})

In [27]:
result.head()

y_pre true value
314   low        low
55    low        low
295  high       high
279  high       high
360   low        low

As you examine these results notice:

There is one mispredict value.

Let's calculate accuracy.

In [28]:
#change data type to categorical data for later accuracy calculation 
result['y_pre']= result['y_pre'].astype('category')
result['true value']= result['true value'].astype('category')

In [29]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import f1_score
#calculate the confusion matrix
tn, fp, fn, tp = confusion_matrix(result['true value'], result['y_pre']).ravel()
print("TP':", tn,"FP:", fp, "FN:", fn, "TP:",tp)

TP': 45 FP: 4 FN: 6 TP: 38


Both true positive and true negative is high, suggesting that model is quite good.

In [30]:
pre_score = precision_score(result['true value'].cat.codes, result['y_pre'].cat.codes)
print('precision score: %.3f'%pre_score)

precision score: 0.905


In [31]:
recall = recall_score(result['true value'].cat.codes, result['y_pre'].cat.codes)
print('recall score: %.3f'% recall)

recall score: 0.864


In [32]:
f1 = f1_score(result['true value'].cat.codes, result['y_pre'].cat.codes)
print('f1 score: %.3f'% recall)

f1 score: 0.864


All precision, recall and f1 scores are quite good, suggesting that the trained model is good.

#### Briefly summarize your findings on using Naïve Bayes.

In this work, I used BernoilliNB as a classifier, which is designed for binary/boolean features. Since  I grouped the target variables to binary, NernoilliNB looks to be a good fit.

I used default setting for this classifier, and use 0.75 of original data as trainning data, and 0.25 of the original data as testing data. The resulting model has a good fit based on high precision, recall and f1 scores. 

I also noticed that another naive bayes model called multinomial is widely used. The multinomial classifier finds the mostly likely class from multiple possibilities, which can be simplified for the Bernoulli or binary case.


#### Is Naïve Bayes more accurate than the regression model you used in Milestone 3?

First, the model I built here is a classification model, the model I built in M3 is a regression model.They are totally different, which is hard to make a comparison between two different models.

In M3, I used linear regression to predict the exact visits. But here, I categorized visits into two groups, one is high, and the other is low.The evaliation matrics are different from regression and classification model. In regression model, we can use R2 score and RMSE; while in classification model, recall, precision and f1 scores are used. 

In M3, R2 is 0.66; while in this work, precision, recall and f1 scores are above 0.9. Although different matrics are not comparable, I'd say this bernoulli naive bayes model is more accurate in classifying the recreation visits.